templates/Template_1_AD_2012.template, templates/Template_1_AD_2012R2.template, templates/Template_2_AD_2012.template, templates/Template_2_AD_2012R2.template, templates/Template_3_AD_2012R2.template
updated regex for dns FQDN , and netbios names to cater for - as a valid part of the name.
Please enter the commit message for your changes. Lines starting
=> updated regex for dns FQDN , and netbios names to cater for - as a valid

scripts/Install-ADDSForest.ps1, templates/ad-1.template
=> Use NetBIOS name when creating AD Forest.

scripts/Install-ADDSForest.ps1, templates/ad-1.template
Reverts aws-quickstart/quickstart-microsoft-activedirectory#20
=> Revert "Use NetBIOS name when creating AD Forest."

templates/ad-3.template
added DirectoryID Output to ad3.template to be used for RDS MSSQL template with AD Authentication.
=> added DirectoryID Output

templates/ad-1.template, templates/ad-2.template
Removed Mapping Section in Favor of SSM Parameter to grab Latest AMI ID
=> changed template from ami mapping to SSM parameter

ci/ad-master-1.json, ci/config.yml, scripts/ConfigDC1.ps1, templates/AWSQuickstart-ActiveDirectoryDS.yml, templates/ad-1.template, templates/ad-master-1.template
Match Recommendation in AD White Paper, Subnet Definition in AD sites and Services now just VPC CIDR.
=> AD Sites Subnet definition to VPC Cidr, not individual subnets

ci/ad-master-1-ssm.json, ci/taskcat.yml, scripts/ConfigDC1-SSM.ps1, scripts/ConfigDC2-SSM.ps1, templates/ad-1-ssm.template, templates/ad-1.template, templates/ad-master-1-ssm.template, templates/ad-master-1.template
added ssm specific templates, added aws::partition pseudo param
=>  added ssm specific templates, added aws::partition pseudo param 

templates/ad-1-ssm.template, templates/ad-1-yaml.template, templates/ad-1.template, templates/ad-2.template, templates/ad-3.template
Updated submodules
Corrected errors flagged by cfn-lint
Updated submodules
=> Corrected errors flagged by cfn-lint

.gitignore, .taskcat.yml, templates/ad-1.template, templates/ad-2.template, templates/ad-3.template, templates/ad-master-1.template, templates/ad-master-2.template, templates/ad-master-3.template
=> Adding regional bucket support in anticipation of SigV2 deprecation

.taskcat.yml, templates/ad-2.template
=> Updating taskcat testing parameters

templates/ad-1-yaml.template, templates/ad-1.template
This PR adds support for multiple partitions to ARNs embedded throughout.
=> Partition Agnositc ARNs

scripts/install-ad-modules.ps1, templates/ad-1.template
when  trying to download modules from powershell gallery, sometimes this messsage appears
WARNING: MSG:UnableToDownload
WARNING: Unable to download the list of available providers. Check your
internet connection.
WARNING: Unable to download from URI 
Adding a line to fix this error from occurring. 
=> fix for MSG:UnableToDownload

scripts/install-ad-modules.ps1, templates/ad-1.template, templates/ad-2.template, templates/ad-3.template, templates/ad-master-1.template, templates/ad-master-2.template, templates/ad-master-3.template
Changed Managed Policies in instance roles for AWS Systems Manager in AD-1.template
=> Updated Systems Manager Managed Policies

.taskcat.yml, scripts/Invoke-EnteriseCaConfig.ps1, scripts/Invoke-MgmtInstanceConfig.ps1, scripts/Invoke-MgmtInstancePostConfig.ps1, templates/ad-1.template, templates/ad-3.template, templates/ad-master-3.template, templates/mgmt-1.template
**Description of changes:**
I added an optional Management Instance for the Managed AD deployment. I also made some minor edits to the CA deployment to make it more stand alone and not dependent on the AD1 template.  
**TaskCat Output:**
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/5527155/taskcat_outputs.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-874f4e5cd87c4247af6c46e32a9cd26a
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-874f4e5cd87c4247af6c46e32a9cd2-VPCStack-1ICO781IYTA7H
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-874f4e5cd87c4247af6c46e32a9cd26-ADStack-LB7DD6S711K5
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-874f4e5cd87c4247af …
=> Adding a Mgmt Inst for ad-3 and Other Fixes

.taskcat.yml, scripts/Post-Config.ps1, templates/ad-1.template, templates/ad-master-1.template
Updated the RDGW sub module to head.  I also added an optional choice to create some default OU.  I also organized the variables so it is easier to read the code.  
*Taskcat Output*
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/5576944/taskcat_outputs.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-2-d07ed925112a4455a6ef6348b5b1f750
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-2-d07ed925112a4455a6ef6348b5b1f7-VPCStack-1GZX6NPICCLXB
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-2-d07ed925112a4455a6ef6348b5b1f75-ADStack-10NZ9N39FXVXR
[INFO   ] : ┣ region: ap-northeast-1
[INFO   ] : ┗ status: CREATE_COMPLETE
[INFO   ] : ┏ stack Ⓜ …
=> Updating Sub Modules & Adding Optional OU Creation

templates/ad-3.template
=> Removing new parameters

.taskcat.yml, templates/ad-1.template, templates/ad-master-1.template, templates/ca-1.template
Simplifying the Enterpise CA deployment option for AD1 by removing the Static IP requirement for the Enterprise CA and setting it to use the PrivateSubnet1ID subnet.  
Taskcat Output:
[tCaT-quickstart-microsoft-activedirectory-ads.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/5619536/tCaT-quickstart-microsoft-activedirectory-ads.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-40e7bd0b19804af182ef7ff9e14803fd
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-40e7bd0b19804af182ef7ff9e14803-VPCStack-STPT9KFGO7DE
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-40e7bd0b19804af182ef7ff9e14803f-ADStack-AKKBH89BVPKP …
=> Simplifying AD1 CA Deployment.

.taskcat.yml, scripts/Invoke-TwoTierOrCaConfig.ps1, scripts/Invoke-TwoTierOrCaPreConfig.ps1, scripts/Invoke-TwoTierSubCaCertIssue.ps1, scripts/Invoke-TwoTierSubCaConfig.ps1, scripts/Invoke-TwoTierSubCaInstall.ps1, scripts/Invoke-TwoTierSubCaPreConfig.ps1, scripts/Post-Config.ps1, scripts/install-ad-modules.ps1, templates/ad-1.template, templates/ad-master-1.template, templates/ca-1-two-tier.template
Adding an optional 2 Tier PKI option for the AD1 Scenario.  I also cleaned up some of the logging in the other scripts to make it easier to read the CW Logs output if there is an error.  
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/5663435/taskcat_outputs.zip)
INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-88f9eb585e6949f49c72442d897d3206
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-88f9eb585e6949f49c72442d897d32-VPCStack-JHY1MKBYL57E
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-88f9eb585e6949f49c72442d897d320-ADStack-4BKOOWYUYMUM
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-88f9eb585e6949f49c72442d89 …
=> Adding Optional Two Tier PKI And Logging Cleanup

templates/ad-1.template, templates/ad-2.template, templates/ca-1-two-tier.template, templates/ca-1.template, templates/mgmt-1.template
Updated the AD stacks to use GP3 instead of GP2.  No other changes made.
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-fe8cab0f986b42889d8c2f23ea6ce668
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-fe8cab0f986b42889d8c2f23ea6ce6-VPCStack-LKFIQMYGOSLS
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-fe8cab0f986b42889d8c2f23ea6ce66-ADStack-BXVM8PBVXM2P
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-fe8cab0f986b42889d8c2f23ea6ce-MgmtStack-1F4GEHH0L8ESG
[INFO   ] : ┣ region: us-west-1
[INFO   ] : ┗ status: CREATE_COMPLETE
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-fe8cab0f986b42889d8c2f23ea6ce668 …
=> Update Templates to use GP3 from GP2

scripts/Invoke-EnteriseCaConfig.ps1, scripts/Invoke-EnteriseCaPreConfig.ps1, scripts/Invoke-TwoTierOrCaConfig.ps1, scripts/Invoke-TwoTierOrCaPreConfig.ps1, scripts/Invoke-TwoTierSubCaCertIssue.ps1, scripts/Invoke-TwoTierSubCaConfig.ps1, scripts/Invoke-TwoTierSubCaInstall.ps1, scripts/Invoke-TwoTierSubCaPreConfig.ps1, templates/ad-1.template, templates/ad-3.template, templates/ad-master-1.template, templates/ad-master-3.template, templates/ca-1-two-tier.template, templates/ca-1.template
Modified the CA templates to support a S3 bucket for CRL Storage.   I also updated the template to allow 1 Tier or 2 Tier CA deployment types with AD3 (AWS Managed Microsoft AD) template.
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/5738115/taskcat_outputs.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-6adffdf0b95d4d6297535235a316bd2c
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-6adffdf0b95d4d6297535235a316bd-VPCStack-MHRY1NZ1GJY2
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-6adffdf0b95d4d6297535235a316bd2-ADStack-CB99KP44JB79
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-6adffdf0b95d4d6297535235a …
=> Updating CA Install to Support S3 And Managed AD

scripts/Invoke-EnterpriseCaConfig.ps1, scripts/Invoke-EnterpriseCaPreConfig.ps1, scripts/Invoke-TwoTierOrCaConfig.ps1, scripts/Invoke-TwoTierSubCaCertIssue.ps1, scripts/Invoke-TwoTierSubCaConfig.ps1, scripts/Invoke-TwoTierSubCaInstall.ps1, scripts/Invoke-TwoTierSubCaPreConfig.ps1, templates/ca-1-two-tier.template, templates/ca-1.template
Fixed some typos, updated script comments and some other minor adjustments.  I also set the CAs to allow the Web Server cert template to be issued.  By default it is not issued and is breaking the ADFS QS as it expects to be able to enroll a Web Server cert.  I also allowed CA RDP from the members of the Domain Members security group.
*TaskCat Output:*
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-20787cdbd4a34e5db815ef460b6038c2
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-20787cdbd4a34e5db815ef460b6038-VPCStack-1AOWTB2W9968T
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-20787cdbd4a34e5db815ef460b6038c-ADStack-VZDFC048ZKWL …
=> Minor Updates and Adjustments to fix ADFS QS

.taskcat.yml, scripts/AD2-NonPromoConfig.ps1, scripts/AD2-Post-Config.ps1, scripts/ConfigDC1.ps1, scripts/ConfigDC2.ps1, scripts/Dns-Config.ps1, scripts/Invoke-MgmtInstanceConfig.ps1, scripts/Invoke-MgmtInstancePostConfig.ps1, scripts/LCM-Config.ps1, scripts/Post-Config.ps1, scripts/install-ad-modules.ps1, templates/ad-1.template, templates/ad-2.template, templates/ad-3.template, templates/ad-master-1.template, templates/ad-master-2.template, templates/ad-master-3.template, templates/mgmt-1.template
Lots of minor text edits and updates.  I also added an option to set the Tombstone lifetime and Delete Objects lifetime of a directory to the AD1 template.  Also if a customer chooses to create the optional OUs I will move the default user and computer location to their respective OUs.
I have fully tested these scenarios manually and with TaskCat
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-67ad07ff57794b7d9388a68eda7ee9ea
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-67ad07ff57794b7d9388a68eda7ee9-VPCStack-1NM3JFH5OVPGY
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-67ad07ff57794b7d9388a68eda7ee9e-ADStack-I87K6OHPSMFG …
=> Many Minor Updates to Text and Logging, along with Tombstone lifetime and Delete Objects lifetime Option

scripts/ConfigDC1.ps1, scripts/ConfigDC2.ps1, scripts/Dns-Config.ps1, scripts/Invoke-MgmtInstanceConfig.ps1
*Issue #*
PKI QS: Script prints password to logs #30
Fixed the logging output to not return the username and password.  
=> Removing Username & Password Credentials From Log

templates/ad-1.template, templates/ad-2.template, templates/ad-3.template, templates/ad-master-1.template, templates/ad-master-2.template, templates/ad-master-3.template, templates/mgmt-1.template
Many minor wording fixes, I also added the WinRM HTTP and HTTPs to the Domain Members Security Group.  Doing so will allow for some future dev options.
*Taskcat of output:*
[AD-taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/6222700/AD-taskcat_outputs.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-07afac6ccf6544b19cd4515389b13b1b
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-07afac6ccf6544b19cd4515389b13b-VPCStack-SMAXULO0BZP9
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-07afac6ccf6544b19cd4515389b13b1-ADStack-1M1J4J91924HT
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-07afac6ccf6544b19cd45153-TwoTierCAStack-RDI9OMVQYR6 …
=> Updating DM SG for WinRM and Wording Fixes

docs/partner_editable/architecture.adoc, docs/partner_editable/product_description.adoc, docs/partner_editable/specialized_knowledge.adoc
=> Edited to align guide with landing page

templates/archive/ca-1.template
=> Fix minor typos.

scripts/Modules/Module-AD/Module-AD.psm1, templates/ad-1.template, templates/ad-1.template.yaml, templates/ad-2.template, templates/ad-2.template.yaml, templates/ad-3.template, templates/ad-3.template.yaml, templates/ad-main-1.template.yaml, templates/ad-main-2.template.yaml, templates/ad-main-3.template.yaml, templates/ad-master-1.template, templates/ad-master-2.template, templates/ad-master-3.template, templates/mgmt-1.template.yaml
Updated AMI to Windows Server 2022. Also various other small fixes.
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-089af10679a14a51b42c65ae40b33ed2
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-089af10679a14a51b42c65ae40b33e-VPCStack-1C2IRBUQEMUJH
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-089af10679a14a51b42c65ae40b33ed-ADStack-ZNHWBX21S7T0
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-089af10679a14a51b42c65ae40b33-MgmtStack-IZRG1YBYVXLY
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-089af10679a14a51b42c65ae-TwoTierCAStack-1UD4ENYJU4KAN
[INFO   ] : ┣ region: us-west-2
[INFO   ] : ┗ status: CREATE_COMPLETE
[INFO   ] : ┏ stack Ⓜ …
=> 2022 AMI and various minor edits.

scripts/Modules/Module-AD/Module-AD.psm1, templates/ad-1.template, templates/ad-1.template.yaml, templates/ad-2.template, templates/ad-2.template.yaml, templates/mgmt-1.template.yaml
Some Minor Updates to the CredSSP function to make it more reliable.  I also updated the CW Log Group Name and Metrics Name Space to include the stack name.  If you look at the output the SA-EAST-1 region failed.  It failed on the CA build which I am currently working on adding the same CredSSP reliability updates.  It did not fail because of anything in the AD QuickStart.
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/files/8393979/taskcat_outputs.zip)
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-microsoft-activedirectory-ad-3-e29a78c19a21404095a9f47c560d2d1d
[INFO   ] : ┣ stack Ⓝ tCaT-quickstart-microsoft-activedirectory-ad-3-e29a78c19a21404095a9f47c560d2d-VPCStack-XYI8WDHZB82S …
=> Minor Fixes

.metadata
=> Creating .metadata

docs/partner_editable/architecture.adoc
=> Removing inaccurate information

templates/ad-1.template.yaml, templates/ad-2.template.yaml, templates/ad-3.template.yaml, templates/ad-main-1.template.yaml, templates/ad-main-2.template.yaml, templates/ad-main-3.template.yaml
=> RegEx update

docs/deployment_guide/partner_editable/overview.adoc
=> Removed reference to Eviden, per conversation w Dave
